### ISSUE TITLE
Closing confirmations page can cause SegFaults

### ISSUE THREAD

**Issue by melvyn2** [melvyn2/PySteamAuth#1]
Sometimes, when closing the confirmations page, a SegFault will occur. This seems like a bug in Qt/PyQt, but we should try to fix this/make a workaround.

**Comment by Jemoka** [comment]
Switch to GitLab already, Melvyn

**Comment by Jemoka** [comment]
https://gitlab.com/jemoka

**Comment by melvyn2** [comment]
Please move this conversation to email <mailto:melvyn.depeyrot@gmail.com> (BTW, I don’t have yours); this is an issue thread.
